var { 
  '@kingjs': {
    rx: { 
      create,
      IObservable,
      IObservable: { Subscribe },
      IObserver: { Next, Complete, Error }
    },
    reflect: { 
      ExportExtension
    },
  }
} = module[require('@kingjs-module/dependencies')]();

var DefaultPredicate = o => o;
var DefaultEqual = (l, r) => l == r;

/**
 * @description Returns an `IObservable` whose values are generated by
 * a private `IObservable` that is activated and refined by emissions
 * from the source `IObservable`.
 */
function where(
  predicate = DefaultPredicate
) {

  var observable = this;

  return create(observer => {
    return observable[Subscribe](
      o => {
        if (!predicate(o))
          return;
        
        observer[Next](o);
      },
      () => observer[Complete](),
      o => observer[Error](o)
    );
  })
}

ExportExtension(module, IObservable, where);
