pushd .index & %* & popd
pushd apply & %* & popd
pushd array\.index & %* & popd
pushd array\make-enumerable & %* & popd
pushd assert & %* & popd
pushd assert-theory & %* & popd
pushd assert-throws & %* & popd
pushd case-at & %* & popd
pushd dictionary & %* & popd
pushd empty-object & %* & popd
pushd enumerable\.index & %* & popd
pushd enumerable\create & %* & popd
pushd enumerable\define & %* & popd
pushd enumerable\for-each & %* & popd
pushd enumerable\from-each & %* & popd
pushd enumerable\odometer & %* & popd
pushd linq\.index & %* & popd
pushd linq\aggregate & %* & popd
pushd linq\all & %* & popd
pushd linq\any & %* & popd
pushd linq\append & %* & popd
pushd linq\average & %* & popd
pushd linq\concat & %* & popd
pushd linq\contains & %* & popd
pushd linq\count & %* & popd
pushd linq\default-equal & %* & popd
pushd linq\default-less-than & %* & popd
pushd linq\distinct & %* & popd
pushd linq\element-at & %* & popd
pushd linq\element-at-or-undefined & %* & popd
pushd linq\empty & %* & popd
pushd linq\except & %* & popd
pushd linq\first & %* & popd
pushd linq\first-or-undefined & %* & popd
pushd linq\group-by & %* & popd
pushd linq\group-join & %* & popd
pushd linq\intersect & %* & popd
pushd linq\join & %* & popd
pushd linq\last & %* & popd
pushd linq\last-or-undefined & %* & popd
pushd linq\max & %* & popd
pushd linq\min & %* & popd
pushd linq\order-by & %* & popd
pushd linq\order-by-descending & %* & popd
pushd linq\prepend & %* & popd
pushd linq\range & %* & popd
pushd linq\repeat & %* & popd
pushd linq\select & %* & popd
pushd linq\select-many & %* & popd
pushd linq\sequence-equal & %* & popd
pushd linq\single & %* & popd
pushd linq\single-or-undefined & %* & popd
pushd linq\skip & %* & popd
pushd linq\skip-while & %* & popd
pushd linq\sum & %* & popd
pushd linq\take & %* & popd
pushd linq\take-while & %* & popd
pushd linq\then-by & %* & popd
pushd linq\then-by-descending & %* & popd
pushd linq\to-array & %* & popd
pushd linq\to-dictionary & %* & popd
pushd linq\to-lookup & %* & popd
pushd linq\union & %* & popd
pushd linq\where & %* & popd
pushd linq\zip & %* & popd
pushd mutate\.index & %* & popd
pushd mutate\copy & %* & popd
pushd mutate\path & %* & popd
pushd mutate\scorch & %* & popd
pushd poset\.index & %* & popd
pushd poset\decode & %* & popd
pushd poset\encode & %* & popd
pushd poset\for-each & %* & popd
pushd poset\inherit & %* & popd
