Object.defineProperties(module.exports, {
  //family: { value: require('@kingjs/descriptor.family') },
  filter: { value: require('@kingjs/descriptor.filter') },
  inherit: { value: require('@kingjs/descriptor.inherit') },
  merge: { value: require('@kingjs/descriptor.merge') },
  mergeWildcards: { value: require('@kingjs/descriptor.merge-wildcards') },
  nested: { value: require('@kingjs/descriptor.nested') },
  normalize: { value: require('@kingjs/descriptor.normalize') },
  object: { value: require('@kingjs/descriptor.object') },
  reduce: { value: require('@kingjs/descriptor.reduce') },
  remove: { value: require('@kingjs/descriptor.remove') },
  scorch: { value: require('@kingjs/descriptor.scorch') },
  update: { value: require('@kingjs/descriptor.update') },
  write: { value: require('@kingjs/descriptor.write') },
});