var { 
  ['@kingjs']: {
    rx: { 
      create,
      IObservable,
      IObservable: { Subscribe },
      IObserver: { Next, Complete, Error }
    },
    reflect: { 
      exportExtension
    },
  }
} = require('./dependencies');

var DefaultEqual = (l, r) => l == r;

/**
 * @description Returns an `IObservable` whose values are generated by
 * a private `IObservable` that is activated and refined by emissions
 * from the source `IObservable`.
 */
function where(callback) {
  var observable = this;

  return create(observer => {
    return observable[Subscribe](
      o => {
        if (!callback(o))
          return;
        
        observer[Next](o);
      },
      () => observer[Complete](),
      o => observer[Error](o)
    );
  })
}

exportExtension(module, IObservable, where);
