var { 
  assert,
  which,
  stringDecoder: { StringDecoder },
  [`@kingjs`]: {
    spawn,    
    rx: { 
      Subject,
      IObserver: { Error },
      IObservable: { Subscribe }
    }
  }
} = module[require('@kingjs-module/dependencies')]()

var Git = 'git'

/**
 * @description Executes a git command using the git executable found on the path.
 * 
 * @param string `command` The git command to execute.
 * 
 * @returns Returns an `IObservable` which streams lines generated by the git command.
 */
function exec(command) {
  return new Subject(observer => {

    which(Git, (error, path) => {

      if (error) {
        observer[Error](error.message)
        return
      }

      spawn(path, command)[Subscribe](observer)
    })
  })
}

module.exports = exec